encoders: {joint_1: 0.792, joint_4: 177.5, joint_6: 87.6, joint_7: 0.033, joint_8: 126.6} #177.4, 87.7 j4 and j6 jitter to
#encoders: {joint_1: 0.792, joint_4: 176.7, joint_6: 86.5, joint_7: 0.033, joint_8: 125.2}
rosdistro: 'kinetic

  '
roslaunch:
  uris: {host_macrobotix2__45379: 'http://macrobotix2:45379/'}
rosversion: '1.12.14

  '
run_id: c80b9192-5f5d-11ea-99e3-d07e3552a9a4
